//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Linq {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource1() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Linq.Resource1", typeof(Resource1).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C:\Users\Janek\Documents\Visual Studio 2015\Projects\Linq\Linq\OutputFiles\Querry1.txt.
        /// </summary>
        internal static string Querry1 {
            get {
                return ResourceManager.GetString("Querry1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C:\Users\Janek\Documents\Visual Studio 2015\Projects\Linq\Linq\OutputFiles\Querry2.txt.
        /// </summary>
        internal static string Querry2 {
            get {
                return ResourceManager.GetString("Querry2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C:\Users\Janek\Documents\Visual Studio 2015\Projects\Linq\Linq\OutputFiles\Querry3.txt.
        /// </summary>
        internal static string Querry3 {
            get {
                return ResourceManager.GetString("Querry3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C:\Users\Janek\Documents\Visual Studio 2015\Projects\Linq\Linq\OutputFiles\Querry4.txt.
        /// </summary>
        internal static string Querry4 {
            get {
                return ResourceManager.GetString("Querry4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C:\Users\Janek\Documents\Visual Studio 2015\Projects\Linq\Linq\OutputFiles\Querry5.txt.
        /// </summary>
        internal static string Querry5 {
            get {
                return ResourceManager.GetString("Querry5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C:\Users\Janek\Documents\Visual Studio 2015\Projects\Linq\Linq\OutputFiles\Querry6.txt.
        /// </summary>
        internal static string Querry6 {
            get {
                return ResourceManager.GetString("Querry6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C:\Users\Janek\Documents\Visual Studio 2015\Projects\Linq\Linq\OutputFiles\Querry7.txt.
        /// </summary>
        internal static string Querry7 {
            get {
                return ResourceManager.GetString("Querry7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C:\Users\Janek\Documents\Visual Studio 2015\Projects\Linq\Linq\OutputFiles\Customers.xml.
        /// </summary>
        internal static string XmlPath {
            get {
                return ResourceManager.GetString("XmlPath", resourceCulture);
            }
        }
    }
}
