//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace framework.DataDeserialize {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class DesirialisationData : global::System.Configuration.ApplicationSettingsBase {
        
        private static DesirialisationData defaultInstance = ((DesirialisationData)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new DesirialisationData())));
        
        public static DesirialisationData Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\Janek\\Documents\\Visual Studio 2015\\Projects\\framework\\framework\\DataDese" +
            "rialize\\XmlFiles\\loginData.xml")]
        public string loginPath {
            get {
                return ((string)(this["loginPath"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\Janek\\Documents\\Visual Studio 2015\\Projects\\framework\\framework\\DataDese" +
            "rialize\\XmlFiles\\SearchData.xml")]
        public string searchData {
            get {
                return ((string)(this["searchData"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\Janek\\Documents\\Visual Studio 2015\\Projects\\framework\\framework\\DataDese" +
            "rialize\\XmlFiles\\AdvansedSearchData.xml")]
        public string advansedSearchData {
            get {
                return ((string)(this["advansedSearchData"]));
            }
        }
    }
}
